rgurl = https://app.getcalley.com/registration.aspx
logurl= https://app.getcalley.com/Login.aspx

username= SeenivasanS
emailid = seenivasan.testing2222@gmail.com
password= cstech
phonenumber=8072474911

userid=seenivasan.testing202@gmail.com
listname= agentlist